---
- name: Preconfiguring Debian servers
  block:
    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 86400

    - name: Set timezone to Europe/Kyiv
      community.general.timezone:
        name: Europe/Kyiv
