---
- name: Install FreePBX 17 on Debian
  hosts: freepbx17
  become: yes
  become_user: root
  vars_files:
      - ./vars/versions.yml
  roles:
      - preconfig
      - set-dns
      - package-install
      - asterisk-install
      - create-asterisk-user
      - configure-apache
      - configure-odbc
      - install-freepbx-ui
      - add-service
      # - role: configure-queue-log
      #   tags: queue-log
      # - role: install-fop2
      #   tags: fop2
